#!/bin/bash

# get user settings
. user_settings.ini
# get global settings
. scripts/global_settings.py

source use-conda
conda activate nnpdf

if [ -z $1 ];
then
echo "supply start id (int)"
exit 1
fi

if [ -z $2 ];
then
echo "supply end id (int)"
exit 1
fi

for i in $(seq -f "%03g" $1 $2)
do
FITNAME=${FITNAME_PREFIX}${i}

echo "uploading: ${FITNAME}"
vp-upload ${FITNAME}
# move to scratch (relies on setting env variable SCRATCH)
echo "moving fit to scratch"
mv ${FITNAME} $SCRATCH/
done
